steps:

- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/romanenko_com:${SHORT_SHA}', '.']

- name: gcr.io/cloud-builders/docker
  args: ['push', 'gcr.io/$PROJECT_ID/romanenko_com']

- name: gcr.io/cloud-builders/gcloud
  args: ['beta', 'run', 'deploy', 'romanenko_com', '--image', 'gcr.io/$PROJECT_ID/romanenko_com:${SHORT_SHA}', '--region', 'us-central1']
  
